# Lychee link checker configuration
accept = [200, 204, 206, 403, 429]
timeout = 20
max_redirects = 10
user_agent = "Mozilla/5.0 (compatible; lychee link checker)"
max_concurrency = 8
exclude_all_private = false
exclude_loopback = true
exclude_link_local = true
exclude_mail = false

# Exclude specific problematic URLs and patterns
exclude = [
    # NPM registry (often blocks automated checkers)
    "https://www.npmjs.com/.*",
    "https://npmjs.com/.*", 
    "https://registry.npmjs.org/.*",
    # ScienceDirect articles (from original .lycheeignore)
    "https://www.sciencedirect.com/science/article/pii/S1053811921010387",
    "https://www.sciencedirect.com/science/article/pii/S0010945221001106",
    "https://www.sciencedirect.com/science/article/pii/S1388245717309069",
    # Localhost and local development URLs
    "http://localhost.*",
    "http://127.0.0.1.*",
    "https://localhost.*",
    # GitHub edit links that may not exist
    ".*/edit/.*",
    # Static files and build artifacts
    ".*/html/_static/.*",
    ".*/_build/.*",
    # Anchor patterns from original config
    ".*anchor.*",
    ".*#.*"
]